### ISSUE TITLE
FsLab Template throws exception when run

### ISSUE THREAD

**Issue by tehcrashxor** [fslaborg/FsLab.Templates#14]
I just installed the FsLab template, created a new project with it, and ran with F5 without making any changes.  It failed with the following:

```
build.fsx(30,58): error FS0039: The field, constructor or member 'With' is not defined

CACHING WARNING
this might happen after Updates...
please open a issue on FAKE and /cc @matthid ONLY IF this happens reproducibly)

Error: System.Exception: We could not find a type similar to '<StartupCode$FSI_0001>.$FSI_0001_Build$fsx' containing a 'main@' method in the cached assembly (C:\Source\Sandbox2\FSharpDataBookFollowAlong\AnalysingDataFollowAlong1\AnalysingDataFollowAlong1/.fake/build.fsx_8E9606F4.dll)!
   at Fake.FSIHelper.runScriptCached@328-4.Invoke(String message) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 328
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1018
   at Fake.FSIHelper.runScriptCached(Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 313
   at Fake.FSIHelper.runFAKEScriptWithFsiArgsAndRedirectMessages(Boolean printDetails, FsiArgs _arg1, IEnumerable`1 env, FSharpFunc`2 onErrMsg, FSharpFunc`2 onOutMsg, Boolean useCache) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 512
Unable to access C:\Source\Sandbox2\FSharpDataBookFollowAlong\AnalysingDataFollowAlong1\AnalysingDataFollowAlong1\.fake\build.fsx_8E9606F4.dll
FsiEvaluationException:

Error:

        build.fsx(30,58): error FS0039: The field, constructor or member 'With' is not defined


Output: [Loading C:\Source\Sandbox2\FSharpDataBookFollowAlong\AnalysingDataFollowAlong1\AnalysingDataFollowAlong1\packages\FSharp.Formatting\FSharp.Formatting.fsx
         Loading C:\Source\Sandbox2\FSharpDataBookFollowAlong\AnalysingDataFollowAlong1\AnalysingDataFollowAlong1\packages\FsLab\Shared\Server.fsx
         Loading C:\Source\Sandbox2\FSharpDataBookFollowAlong\AnalysingDataFollowAlong1\AnalysingDataFollowAlong1\packages\FsLab\Shared\Styles.fsx
         Loading C:\Source\Sandbox2\FSharpDataBookFollowAlong\AnalysingDataFollowAlong1\AnalysingDataFollowAlong1\packages\FsLab\FsLab.fsx
         Loading C:\Source\Sandbox2\FSharpDataBookFollowAlong\AnalysingDataFollowAlong1\AnalysingDataFollowAlong1\build.fsx]


Input: C:\Source\Sandbox2\FSharpDataBookFollowAlong\AnalysingDataFollowAlong1\AnalysingDataFollowAlong1\build.fsx

Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System.Exception: Operation failed. The error text has been print the error stream. To return the corresponding FSharpErrorInfo use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.EvalScript(String filePath)
   at Yaaf.FSharp.Scripting.Helper.evalScript@1097.Invoke(String arg00) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1097
   at Yaaf.FSharp.Scripting.Helper.save_@1072-2.Invoke(Unit unitVar0) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1073
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1018
   at Yaaf.FSharp.Scripting.Helper.redirectOut@1044[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err, FSharpFunc`2 f) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1051
   at Yaaf.FSharp.Scripting.Helper.save_@1071-1.Invoke(String text) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1072
   --- End of inner exception stack trace ---
   at Yaaf.FSharp.Scripting.Helper.save_@1071-1.Invoke(String text) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1080
   at Yaaf.FSharp.Scripting.Helper.session@1100.Yaaf-FSharp-Scripting-IFsiSession-EvalScriptWithOutput(String ) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1102
   at Fake.FSIHelper.runScriptUncached(Boolean useCache, String scriptPath, IEnumerable`1 fsiOptions, Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 471
build.fsx(30,58): error FS0039: The field, constructor or member 'With' is not defined
```

**Comment by tpetricek** [comment]
It looks like a version mismatch issue somewhere - I'll investigate on Tuesday!

**Comment by tpetricek** [comment]
I started looking into this and found one issue (https://github.com/fsharp/FAKE/issues/1372), though this is probably not the one you reported here.

**Comment by tpetricek** [comment]
Should be fixed now - I needed re-release FsLab.Runners after changing the templates here.

You do not need to reinstall the VS template, just create new project and it should work.

**Comment by tehcrashxor** [comment]
Yep, that worked.  Thanks.
